# define embedding specific data path
train:
  precomputed_articles: ${oc.env:WORKDIR}/dataset/mind/${dataset_type}/processed/train/article_inputs_transformer.pkl
valid:
  precomputed_articles:  ${oc.env:WORKDIR}/dataset/mind/${dataset_type}/processed/valid/article_inputs_transformer.pkl
model: models/transformers/bert-base-uncased
